### PR TITLE
Added authors model, validation and testing

### LINKED ISSUE #24: Create Author Model
Create a new Category model. **Questions will have-many Authors** and **Authors will have-many Questions**.

Django will automatically create the **question_authors** table if you do the first option seen in [this video ](https://www.youtube.com/watch?v=-HuTlmEVOgU)

Add validation to ensure a question cannot have the same author twice.

Add a test to validate that a question cannot have the same author twice.

Screenshot 2021-04-29 at 2 59 44 PM

### PR DESCRIPTION
**Pull request by ApprenticeofEnder**
Resolved #24. Added author model, same as Categories effectively

### CODE REVIEW

**Review by MathyouMB — APPROVED** [review]
LGTM. Before we merge though, could we add Authors to the question serializer? That way will also be closing #26.

**Comment by ApprenticeofEnder** [comment]
> LGTM. Before we merge though, could we add Authors to the question serializer? That way will also be closing #26.

Will do!

**Comment by ApprenticeofEnder** [comment]
FINALLY.

**Review by MathyouMB — APPROVED** [review]
LGTM :)

**Pull request merged**
