### PR TITLE
Fixes #19

### LINKED ISSUE #19: Add Difficulty column to Questions
Please add the **difficulty column** **(string)** to the **questions** model. Please also update the corresponding **serializers** so that difficulty can be accessed via its corresponding endpoints.

On the model, use the **following syntax** to ensure the difficulty can be of the following options: **Easy, Medium, and Hard.**

```
format = models.CharField(
        choices=(
            ("t", "text"),
            ("h", "html"),
            ("m", "mathjax"),
        ),
        max_length=1,
    )
```

Screenshot 2021-04-29 at 1 12 53 PM

### PR DESCRIPTION
**Pull request by pmkuny**
* Co-authored by Alec Dutcher @aidutcher
* Adds difficulty drop-down as requested - we used the same syntax as
`format` which takes single letters, so for this it's `'e', 'easy', 'm',
'medium'` etc.
* We had to manually edit the database otherwise Django was throwing an
error about the missing difficulty column. This required adding a
`difficulty varchar(6)` column to the end of the database table
`codechallenges_question`. I didn't encounter any errors with this while
viewing and adding questions from the admin panel, but it's good to note in case column order matters.

The full table create schema is now:
```
CREATE TABLE IF NOT EXISTS "codechallenges_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(150) NOT NULL, "body" text NOT NULL, "format" varchar(1) NOT NULL, "answer" varchar(150) NOT NULL, "release_date" date NOT NULL, "expiration_date" date NOT NULL, event_id" integer NULL REFERENCES "codechallenges_codechallengeevent" ("id") DEFERRABLE INITIALLY DEFERRED, "difficulty" varchar(6));
```

### CODE REVIEW

**Comment by pmkuny** [comment]
The force push was to revert a change to the database settings that I committed by mistake.

**Comment by MathyouMB** [comment]
Hey @pmkuny! This model change looks good! 😊

In order for us to properly add the new field to the questions table, you will need to add a migration. Django has an awesome system for generating new migrations. If you run `python manage.py makemigrations` Django will automatically create a migration that reflects the change you made to the Questions table. After creating the migration, you can migrate it by running `python manage.py migrate`.  After you commit this migration, it will be ready to merge! 🚢

**Review by MathyouMB — CHANGES_REQUESTED** [review]
Please add a Django generated migration that adds the difficulty field to the questions table.

**Comment by pmkuny** [comment]
Added in those migrations. Thanks for the explanation, that was super helpful!

**Review by MathyouMB — APPROVED** [review]
I tested out your change and it looks good! You're good to merge!

**Comment by pmkuny** [comment]
I don't think I have merge privileges, but appreciate it!

**Pull request merged**
